name: CI

env:
  APK_NAME: "dnsmasq"
  APK_VERSION: "2.91-r0"
  IMAGE_TAG: "2.91.0.0"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and push the docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build `${{env.APK_NAME}}` docker image
        run: >-
          docker build .
          --tag $APK_NAME
          --build-arg APK_NAME=$APK_NAME
          --build-arg APK_VERSION=$APK_VERSION

      - name: Login to container registry
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        env:
          GITHUB_ACTOR: ${{github.actor}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Push `${{env.APK_NAME}}` docker image
        if: github.event_name == 'release'
        run: |
          docker tag $NAME $IMAGE_ID:$TAG
          docker tag $NAME $IMAGE_ID:latest
          docker push --all-tags $IMAGE_ID
        env:
          IMAGE_ID: ghcr.io/${{github.repository_owner}}/${{env.APK_NAME}}
